apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIyMDEzMDEyMzkwM1oXDTMyMDEyOTEyMzkwM1owFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOqz
    EYUIEPUK1SPffG8MqHbTJwkw0/6ku0FkQEYN4u47lo5ztF6XBquSbOID+chLG1ad
    NLsJEtH09amsmBvsAf5nD8lUVaXEnrTKQpXrSoHMzKrqklEwlxX2UIhwmFLXCj5B
    BZ3eeOYLCYYDNTVKcAhnL7jdv1vIIJ07jeKIIFNZWNfMx/Q1JKSB6HxjxNP/onHI
    YEvjMDRLDKOTQE1Ui11+yf2lQj7PePG5/dWpUG76FXWexQYeJkN6cWZFHchuaHNv
    /dc1Ie2P8sTvLLpEqFKzcwP/IiM2FZgbNryDtv2to6bpPmyKEP4hiGOj9t6Kx4Dw
    MBgwFIWfkHdyHyzcMpkCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBQ3WurpVlzDVHTOZ5lSg2jRyNfTbzANBgkqhkiG9w0BAQsFAAOCAQEAyx2Oh94Y
    9efP2TAw6NDNU60thMgFyngsKSt/jTv1qigPN3lR2UnZDoiGVyGQY/eEYqpQJOfR
    E4GwyRoWGt2RbrozeuUR9YBvuxBaVoCMV7mjfktnCH5EGu1YfF5IjRM9FvD/+Rhy
    qdwryQwIY5jkZz+SnAdhfBXn7rXSvmeuzo4RbVUWcNKkBRpYJEMOaCmq69EyZ+kw
    GESdOXA3uOX4JIvwaJje1g80Eo/KkWfpJku0m1oAPmU4ib7ZZua/fUl8gKsxrbtr
    fmK26JDcUqNcJAE2QbkLSr5cMY3vuiVszhPW1DAwTFONvin/y8ij2veLYK9Nh55t
    0k798hdc8r1jsA==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/description: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-31T15:23:58Z"
  name: kube-root-ca.crt
  namespace: guestbook
