apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeU1ERXpNREV5TXprd00xb1hEVE15TURFeU9URXlNemt3TTFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT3F6CkVZVUlFUFVLMVNQZmZHOE1xSGJUSndrdzAvNmt1MEZrUUVZTjR1NDdsbzV6dEY2WEJxdVNiT0lEK2NoTEcxYWQKTkxzSkV0SDA5YW1zbUJ2c0FmNW5EOGxVVmFYRW5yVEtRcFhyU29ITXpLcnFrbEV3bHhYMlVJaHdtRkxYQ2o1QgpCWjNlZU9ZTENZWUROVFZLY0Fobkw3amR2MXZJSUowN2plS0lJRk5aV05mTXgvUTFKS1NCNkh4anhOUC9vbkhJCllFdmpNRFJMREtPVFFFMVVpMTEreWYybFFqN1BlUEc1L2RXcFVHNzZGWFdleFFZZUprTjZjV1pGSGNodWFITnYKL2RjMUllMlA4c1R2TExwRXFGS3pjd1AvSWlNMkZaZ2JOcnlEdHYydG82YnBQbXlLRVA0aGlHT2o5dDZLeDREdwpNQmd3RklXZmtIZHlIeXpjTXBrQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJRM1d1cnBWbHpEVkhUT1o1bFNnMmpSeU5mVGJ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF5eDJPaDk0WQo5ZWZQMlRBdzZORE5VNjB0aE1nRnluZ3NLU3QvalR2MXFpZ1BOM2xSMlVuWkRvaUdWeUdRWS9lRVlxcFFKT2ZSCkU0R3d5Um9XR3QyUmJyb3pldVVSOVlCdnV4QmFWb0NNVjdtamZrdG5DSDVFR3UxWWZGNUlqUk05RnZELytSaHkKcWR3cnlRd0lZNWprWnorU25BZGhmQlhuN3JYU3ZtZXV6bzRSYlZVV2NOS2tCUnBZSkVNT2FDbXE2OUV5WitrdwpHRVNkT1hBM3VPWDRKSXZ3YUpqZTFnODBFby9La1dmcEprdTBtMW9BUG1VNGliN1padWEvZlVsOGdLc3hyYnRyCmZtSzI2SkRjVXFOY0pBRTJRYmtMU3I1Y01ZM3Z1aVZzemhQVzFEQXdURk9OdmluL3k4aWoydmVMWUs5Tmg1NXQKMGs3OThoZGM4cjFqc0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Z3Vlc3Rib29r
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltUlhjbk54YmxWWExYVmFaM1Z4VEVORWRtMTRjRGRqVHpReGF6UmFRMGxWVFV4TFRqUTNhRE5WVFVraWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpuZFdWemRHSnZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMWpibmg0WmlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pT1RnNE5qWXlZVGN0TW1JM05TMDBOak15TFdGak5qUXRZelV5TXpNd09ERXpaR1JpSWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tZDFaWE4wWW05dmF6cGtaV1poZFd4MEluMC5lUERhRWp2UHBoWlRTaGZTRzFHUkNaajYwQy1SOWZJNnZmbjVqdEF1b3pwSTJsbmp4aUdMd2twN1FOMUVMYU41bHVrSXVPQklObWlyQ3BqSjlYM2VLaGpYODlMa1ZvQUh0YU51Q3Q1RGlwQk11UFMwMHREbl9ubVliOXhWQW85N0RzRkJZV0FsSHF2X2NmMmtFVV9qRk10TE4tMlZuNm5wR19NbDJ3czg4eEJiZmRQR3hyZXNrWUVTM2VCMGp0Vzk5U21KTU4yeDdVNVZfY1hfdHpFb1ZjaWVvLTFETUlwZktFdzdvQ2lkNGRGQUtIVjMzdHB3a2h6enBQVnJ2OGp0WHBOMUU1ZFRLOVlEVV9QTmVuTGtta3JnZThQbkU5a1RGMG1YUDQyZDhPYkNmUU9qdmZ3bGJuSlFJVnc3UWgyeFBGNDZMSl8xWU8zai1fZDRTZ1UtT3c=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 988662a7-2b75-4632-ac64-c52330813ddb
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-31T15:23:58Z"
  name: default-token-cnxxf
  namespace: guestbook
type: kubernetes.io/service-account-token
